site_name: Spoofax 3
site_description: Spoofax 3 documentation website

nav:
  - Home: index.md
  - Tutorials:
      - tutorial/install.md
      - tutorial/create_language_project.md
#  - Guides:
#      - guide/adding_commands_and_menus.md
  - Reference:
      - reference/language_definition.md
      - reference/anatomy_language_implementation.md
  - Background:
      - background/documentation.md
      - background/motivation.md
      - background/key_ideas.md
      - background/status.md
  - Releases:
      - release/download.md

theme:
  name: material
  language: en
  logo: assets/spoofax.svg
  favicon: assets/spoofax.png
  palette:
    primary: indigo
    accent: indigo
  font:
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top

extra_css:
  - extra.css

repo_name: metaborg/spoofax-pie
repo_url: https://github.com/metaborg/spoofax-pie

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - macros:
      module_name: docs/macro
  - git-revision-date:
      enabled_if_env: CI
