site_name: Spoofax 3
site_description: Spoofax 3 documentation website

nav:
  - Home: index.md
  - Tutorials:
      - tutorial/install.md
      - tutorial/create_language_project.md
#  - Guides:
#      - guide/adding_commands_and_menus.md
  - Reference:
      - reference/anatomy_language_implementation.md
  - Background:
      - background/documentation.md
      - background/motivation.md
      - background/key_ideas.md
      - background/status.md
  - Releases:
      - release/download.md

theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top

extra_css:
  - extra.css

repo_name: metaborg/spoofax-pie
repo_url: https://github.com/metaborg/spoofax-pie

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - macros
  - git-revision-date:
      enabled_if_env: CI

extra:
  os:
    windows: ":fontawesome-brands-windows: Windows"
    linux: ":fontawesome-brands-linux: Linux"
    macos: ":fontawesome-brands-apple: macOS"
  download:
    dev:
      lwb:
        eclipse:
          jvm:
           windows: ":fontawesome-brands-windows: [Windows 64-bit with embedded JVM](https://artifacts.metaborg.org/service/local/artifact/maven/redirect?r=snapshots&g=org.metaborg&a=spoofax.lwb.eclipse.repository&c=spoofax3-win32-x86_64-jvm&p=zip&v=LATEST)"
           macos: ":fontawesome-brands-apple: [macOS 64-bit with embedded JVM](https://artifacts.metaborg.org/service/local/artifact/maven/redirect?r=snapshots&g=org.metaborg&a=spoofax.lwb.eclipse.repository&c=spoofax3-macosx-x86_64-jvm&p=zip&v=LATEST)"
           linux: ":fontawesome-brands-linux: [Linux 64-bit with embedded JVM](https://artifacts.metaborg.org/service/local/artifact/maven/redirect?r=snapshots&g=org.metaborg&a=spoofax.lwb.eclipse.repository&c=spoofax3-linux-x86_64-jvm&p=zip&v=LATEST)"
          windows: ":fontawesome-brands-windows: [Windows 64-bit](https://artifacts.metaborg.org/service/local/artifact/maven/redirect?r=snapshots&g=org.metaborg&a=spoofax.lwb.eclipse.repository&c=spoofax3-win32-x86_64&p=zip&v=LATEST)"
          macos: ":fontawesome-brands-apple: [macOS 64-bit](https://artifacts.metaborg.org/service/local/artifact/maven/redirect?r=snapshots&g=org.metaborg&a=spoofax.lwb.eclipse.repository&c=spoofax3-macosx-x86_64&p=zip&v=LATEST)"
          linux: ":fontawesome-brands-linux: [Linux 64-bit](https://artifacts.metaborg.org/service/local/artifact/maven/redirect?r=snapshots&g=org.metaborg&a=spoofax.lwb.eclipse.repository&c=spoofax3-linux-x86_64&p=zip&v=LATEST)"
